apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-todos-cron
  namespace: todos-db-namespace
  labels:
    run: curl
spec:
  schedule: "59 16 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: curlimages/curl:7.73.0
            args:
            - sh
            - -c
            - "DAILY_TODO_URL=$(sh -c echo -n ; curl -sI https://en.wikipedia.org/wiki/Special:Random |grep 'location:' |awk '{print $2}')"
          restartPolicy: OnFailure