apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: todo-url
  namespace: todos-db-namespace
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-url
            image: jylhakos/todo-backend-db:2.9.14
            command: ["/bin/sh"]
            args: ["/etc/config/shell-script.sh"]
            volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: false
            - name: data-volume
              mountPath: /etc/data
              readOnly: false
          volumes:
          - name: config-volume
            configMap:
              name: shell-script
              defaultMode: 0644
          - name: data-volume
            emptyDir: {}
          restartPolicy: Never

      