apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: podinfo
  namespace: todos-db-namespace
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todos-backend-db-dep
  service:
    port: 9898
  analysis:
    interval: 10s
    threshold: 5
    stepWeight: 10
    maxWeight: 100
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m