kind: Deployment
apiVersion: apps/v1
metadata:
  name: todos-backend-db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-backend-db
  template:
    metadata:
      labels:
        app: todos-backend-db
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: postgresql-pv
      containers:
        - name: todo-backend-db
          image: jylhakos/todo-backend-db:3.0.7
          env:
            - name: DB_HOST
              value: postgresql-svc
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: PGPASSWORD
              value: postgres
            #- name: POSTGRES_PASSWORD
            #  valueFrom:
            #    secretKeyRef:
            #      name: secret-postgres
            #      key: password
          envFrom:
            - configMapRef:
                name: app-db-env
          volumeMounts:
          - name: data-volume
            mountPath: /var/lib/postgresql/data
            subPath: postgres
          resources:
            limits:
              cpu: "150m"
              memory: "200Mi"
