apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-app
  name: postgresql-svc
  namespace: todos-db-namespace
spec:
  clusterIP: None
  ports:
  - name: postgresql-port
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql-db
  type: ClusterIP
---
