apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: go-app
type: Opaque
data:
  # Base64 encoded values
  # postgres / password
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  
  # To generate base64 encoded values, use:
  # echo -n "your-password" | base64
