apiVersion: v1
kind: Secret
metadata:
    name: pixabay-apikey
data:
    API_KEY: ENC[AES256_GCM,data:YT5/kjy1+lhm8cLcwJig4L8E4/V1G78ZyKGEu9YaSviF9Q==,iv:HP6e548eEjoCfdwxNbIwZLl+wyFjxPtskdosG7WTDeA=,tag:DzDk+ovtAbgfZ8bqp61B4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yqdy6ymr0f4aacrq5ehamcp2ua8amj26cjeyrzu9s2k7g9cgz43snaafyy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aHd4WVlkNHkxS3VnckZZ
            bDZDeVV3OHIwOWlaeXZCTmZSVkVpTG5RWTNNCktEVjc2OUVWWmlFbElLdnRDQmNs
            cmxheDBxWmRvUzVqV0dObk0xSGR1Q2sKLS0tIHdQcVVhSDY2M2FMNTlma2E4ZEdC
            Smc2UlRKb2hrZnduUXEyOXBTYkpCODAKnWmoxkuaWPUmTv0En8b4jaYoyWucjLKO
            6mG+ioYuwzIX+Og4E/bCAyfChoDhj8ITWQaIQEftmioaPwxTcAasvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-20T03:17:24Z"
    mac: ENC[AES256_GCM,data:7LTweV4H5hT+P4k5U/GPM0Qzr2IzDFXBEQDWru9hOGcZed9lcAZPyC08Di5bWqNPGQFYE5j3/MnM8NHyrKeco1JWLuEeTf7MMemsJhao0cVFkR9SpxCUisThmSSdkRaG08L07BDfm/uo3hfnkHCTIZrgZtc+SMnr0ckiD0szBrM=,iv:z62icfJhSSpM77cXB6jeHJozkQnLdAMnFtPilo4CAWU=,tag:hb2udOCdubpYPDwWrRVcHg==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.1
