apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: todos-namespace
spec:
  type: ClusterIP
  selector:
    app: todos-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3002