version: '3.8'
services:
  react-frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
