apiVersion: v1
kind: Service
metadata:
  name: app-2-http-svc
  namespace: app-http-namespace
spec:
  type: ClusterIP
  selector:
    app: app-2-http
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
