name: Release application
on:
  push:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: app-3-dwk-cluster
  GKE_ZONE: europe-west4-a
  IMAGE: dwk-environments
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Build
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT-BACKEND/$IMAGE-BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
          .
      run: |-
        docker build \
          --tag "gcr.io/$PROJECT-FRONTEND/$IMAGE-FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
          .
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT-BACKEND/$IMAGE-BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
      run: |-
        docker push "gcr.io/$PROJECT-FRONTEND/$IMAGE-FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: Deploy
      run: |-
        kustomize edit set image gcr.io/PROJECT-BACKEND/IMAGE-BACKEND=gcr.io/$PROJECT-BACKEND/$IMAGE-BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment $IMAGE-BACKEND
        kustomize edit set image gcr.io/PROJECT-FRONTEND/IMAGE-FRONTEND=gcr.io/$PROJECT-FRONTEND/$IMAGE-FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        kustomize build . | kubectl apply -f -
        kubectl rollout status deployment $IMAGE-FRONTEND
        kubectl get services -o wide
    