apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-0-2-shared-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-0-2-shared
  template:
    metadata:
      labels:
        app: app-0-2-shared
    spec:
      volumes:
        - name: shared-text
          persistentVolumeClaim:
            claimName: shared-claim
      containers:
        - name: app-2-shared
          image: jylhakos/app-2-shared
          volumeMounts:
          - name: shared-text
            mountPath: /usr/src/app/files
        - name: app-0-shared
          image: jylhakos/app-0-shared
          volumeMounts:
          - name: shared-text
            mountPath: /usr/src/app/files
