apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/service-response.yaml
- ./manifests/deployment-frontend.yaml
images:
- name: PROJECT/IMAGE_FRONTEND
  newName: jylhakos/todo-frontend-db:2.0.8
