# This is deployment workflow with Github Actions

name: Release branch

on:
  push:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: app-3-dwk-cluster
  GKE_ZONE: europe-west4-a
  IMAGE: todos-backend
  DEPLOYMENT_NAME: todos-backend-db-dep
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
        context: ./todo-backend-db
        dockerfile: ./todo-backend-db/Dockerfile
    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Build
      run: |-
        docker build --file ./todo-backend-db/Dockerfile --tag 3.0.0 \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
          .
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: List Directory
      run: ls -l
    - name: Deploy
      run: |-
        kubectl create namespace ${GITHUB_REF#refs/heads/} || true
        kubectl config set-context --current --namespace=${GITHUB_REF#refs/heads/}
        kustomize edit set namespace ${GITHUB_REF#refs/heads/}
        kustomize edit set image gcr.io/PROJECT_ID/IMAGE_BACKEND=gcr.io/$PROJECT_ID/$IMAGE_BACKEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        kubectl apply -k .
        kubectl rollout status deployment $IMAGE_BACKEND
        #kustomize edit set image gcr.io/PROJECT_ID/IMAGE_FRONTEND=gcr.io/$PROJECT_ID/$IMAGE_FRONTEND:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        #kubectl apply -k ./kustomization/frontend
        #kubectl rollout status deployment $IMAGE_FRONTEND
