apiVersion: v1
kind: Service
metadata:
  name: app-2-db-svc
  namespace: app-db-namespace
spec:
  type: ClusterIP
  selector:
    app: app-2-db
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
