apiVersion: v1
kind: Service
metadata:
  name: app-0-db-svc
  namespace: app-db-namespace
spec:
  type: NodePort
  selector:
    app: app-0-db
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000
