apiVersion: v1
kind: Service
metadata:
  name: postgresql-svc
  namespace: app-db-namespace
  labels:
    app: postgresql
spec:
  ports:
  - port: 5432
    name: postgresql-port
  clusterIP: None
  selector:
    app: postgresql-db