apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-config
  namespace: ml-pipeline
data:
  backend-url: "http://ml-backend-service:5000"
  model-path: "/src/model"
  data-path: "/src/data"
  images-path: "/src/imgs"
  flask-env: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: ml-secrets
  namespace: ml-pipeline
type: Opaque
data:
  # Add any sensitive configuration here (base64 encoded)
  # Example: database-url: <base64-encoded-url>
