apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ml-pipeline
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'ml-backend'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - ml-pipeline
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: ml-backend-service
    - job_name: 'ml-frontend'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - ml-pipeline
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: ml-frontend-service
---
apiVersion: v1
kind: Service
metadata:
  name: ml-monitoring
  namespace: ml-pipeline
  labels:
    app: monitoring
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
  - name: grafana
    port: 3001
    targetPort: 3000
  selector:
    app: monitoring
