apiVersion: v1
kind: ServiceAccount
metadata:
  name: ml-pipeline-sa
  namespace: ml-pipeline
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_ACCOUNT_ID:role/EKS_ML_Pipeline_Role  # Replace with your IAM role ARN
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ml-pipeline
  name: ml-pipeline-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-pipeline-rolebinding
  namespace: ml-pipeline
subjects:
- kind: ServiceAccount
  name: ml-pipeline-sa
  namespace: ml-pipeline
roleRef:
  kind: Role
  name: ml-pipeline-role
  apiGroup: rbac.authorization.k8s.io
