kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: postgresql-ss
spec:
  serviceName: postgresql-svc
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          env:
            - name: POSTGRES_INITDB_ARGS
              value: "-A md5"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: PGDATA
              value: "/var/lib/postgresql/data"
            - name: DB_PORT
              value: "5432"
            - name: DB_SCHEMA
              value: "postgres"
          #envFrom:
          #  - configMapRef:
          #      name: app-db-env
          ports:
          - containerPort: 5432
            name: postgresql-port
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi