apiVersion: v1
kind: Secret
metadata:
  name: go-app-secret
  namespace: go-app
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # mypassword
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==  # redispassword
