name: Release kube-cluster-dwk

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - 'manifests'
      - '.github/workflows/workflow.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: app
        push: true
        tags: jylhakos/kube-cluster-dwk:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    # Set up kustomize
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1

    # Update yamls
    - name: Update yamls
      working-directory: manifests
      run: |-
        kustomize edit set image IMAGE_PLACEHOLDER=jylhakos/kube-cluster-dwk:${{ github.sha }}

    # Commit and push
    - uses: EndBug/add-and-commit@v7
      with:
        add: 'manifests/kustomization.yaml'
        message: New version release for kube-cluster-dwk
      
