# $ docker build -t jylhakos/kube-cluster-dwk .
# $ docker push jylhakos/kube-cluster-dwk
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: jylhakos/kube-cluster-dwk
  newTag: ecfd0e8d4da848d6c46bfd14cf63257d7ce7f719
