apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: dummysites.dummysite.dwk
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: dummysite.dwk
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DummySite
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: dummysites
    # singular name to be used as an alias on the CLI and for display
    singular: dummysite
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - dummy
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                #length:
                #  type: integer
                #delay:
                #  type: integer
                image:
                  type: string
                website_url:
                  type: string
                html:
                  type: string
      additionalPrinterColumns:
        #- name: Length
        #  type: integer
        #  description: The length of the dummysite
        #  jsonPath: .spec.length
        #- name: Delay
        #  type: integer
        #  description: The length of time (ms) between executions
        #  jsonPath: .spec.delay
        - name: WebsiteUrl
          type: string
          description: URL
          jsonPath: .spec.website_url
        - name: HTML
          type: string
          description: HTML from URL
          jsonPath: .spec.html