apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./manifests/service-backend.yaml
- ./manifests/ingress-backend.yaml
- ./manifests/deployment-backend.yaml
images:
- name: PROJECT/IMAGE_BACKEND
  newName: jylhakos/todo-backend-db:3.0.0
