apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: ml-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'ml-backend'
      static_configs:
      - targets: ['ml-backend-service:5000']
      metrics_path: '/metrics'
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - ml-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: ml-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
      volumes:
      - name: config
        configMap:
          name: monitoring-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: ml-app
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP
