apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  fsType: ext4
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-storage
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-utils
  fileSystemId: fs-xxxxxxxxx  # Replace with actual EFS ID
  directoryPerms: "0755"
volumeBindingMode: Immediate
reclaimPolicy: Retain
