apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/deployment.yaml
- manifests/service.yaml
images:
- name: PROJECT-BACKEND/IMAGE-BACKEND
  newName: jylhakos/todo-backend-db:3.0.0
- name: PROJECT-FRONTEND/IMAGE-FRONTEND
  newName: jylhakos/todo-response-db:2.0.9