apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-containers-cpu-usage
  namespace: todos-db-namespace
spec:
  metrics:
  - name: backend-containers-cpu-usage
    initialDelay: 2m
    interval: 30s
    count: 60 
    successCondition: result < 10
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1638-prometheus.prometheus.svc:9090
        query: |
          scalar(
            sum (rate (container_cpu_usage_seconds_total{namespace="todos-db-namespace", container_name!="POD", container=~"todo-backend-db"}[10m])) / sum (machine_cpu_cores{}) * 100
          )
