apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-0-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-0
  template:
    metadata:
      labels:
        app: app-0
    spec:
      containers:
        - name: app-0
          image: jylhakos/app-0:1.03
