version: '3.8'

services:
  react-frontend:
    build: .
    ports:
      - "3000:5000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
