apiVersion: v1
kind: Service
metadata:
  name: app-2-db-svc
spec:
  type: LoadBalancer
  selector:
    app: app-2-db
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3001
