# This is deployment workflow with Github Actions

name: Release todo-response-db
on:
  push:
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: app-3-dwk-cluster
  GKE_ZONE: europe-west4-a
  IMAGE: todos-frontend
  DEPLOYMENT_NAME: todos-frontend-db-dep
jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        export_default_credentials: true
        context: ./todo-response-db
        dockerfile: ./todo-response-db/Dockerfile
    - run: gcloud --quiet auth configure-docker
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    - name: Build
      run: |-
        docker build --file ./todo-response-db/Dockerfile --tag 3.0.0 \
          --tag "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA" \
          .
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA"
    - name: Set up Kustomize
      uses: imranismail/setup-kustomize@v1
    - name: List Directory
      run: ls -l
    - name: Deploy
      run: |-
        kustomize edit set image gcr.io/PROJECT_ID/IMAGE=gcr.io/$PROJECT_ID/$IMAGE:${GITHUB_REF#refs/heads/}-$GITHUB_SHA
        kustomize build ./todo-response-db/. | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
