apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-backend-db-dep
  namespace: todos-db-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-backend-db
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todos-backend-db
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: postgresql-svc
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: BACKEND_PORT
          value: "3002"
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: NATS_URL
          value: nats://todos-nats:4222
        envFrom:
        - configMapRef:
            name: app-db-env
        image: jylhakos/todo-backend-db:v4.24
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 60
        name: todo-backend-db
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3002
          initialDelaySeconds: 15
          periodSeconds: 30
        volumeMounts:
        - mountPath: /etc/data
          name: data-volume
      volumes:
      - emptyDir: {}
        name: data-volume
---
