apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-backend-db-dep
  namespace: todos-db-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-backend-db
  template:
    metadata:
      labels:
        app: todos-backend-db
    spec:
      containers:
        - name: todo-backend-db
          image: PROJECT-BACKEND/IMAGE-BACKEND
          volumeMounts:
            - name: data-volume
              mountPath: /etc/data
              readOnly: false
          env:
            - name: DB_HOST
              value: postgresql-svc
          envFrom:
            - configMapRef:
                name: app-db-env
      volumes:
          - name: data-volume
            emptyDir: {}
